/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Character, Skill, BreathStyle, CorpsRank } from '../models/types.ts';

// Reusable skill library
const SKILLS: Record<string, Skill> = {
  water_surface_slash: {
    id: 'sk_water_1',
    name: '壱ノ型 水面斬り',
    katagaki: '水の呼吸',
    breathStyle: 'water',
    bpCost: 4,
    power: 120,
    target: 'single',
    effectType: 'damage',
    description: '交差するように水平に放つ水流の斬撃。',
    animation: 'slash_water'
  },
  water_wheel: {
    id: 'sk_water_2',
    name: '弐ノ型 水車',
    katagaki: '水の呼吸',
    breathStyle: 'water',
    bpCost: 8,
    power: 155,
    target: 'single',
    effectType: 'damage',
    description: '垂直に宙を舞い、円を描くように斬り下ろす。',
    animation: 'slash_water'
  },
  water_flow: {
    id: 'sk_water_10',
    name: '拾ノ型 生生流転',
    katagaki: '水の呼吸',
    breathStyle: 'water',
    bpCost: 20,
    power: 240,
    target: 'single',
    effectType: 'damage',
    description: '回転しながら龍のような激流となって放つ最大威力の連撃。',
    animation: 'slash_water'
  },
  water_dead_calm: {
    id: 'sk_water_11',
    name: '拾壱ノ型 凪',
    katagaki: '水の呼吸',
    breathStyle: 'water',
    bpCost: 18,
    power: 190,
    target: 'all',
    effectType: 'damage',
    description: '間合いに入った攻撃を静寂の水面のように無へと返す冨岡義勇の独自技。',
    animation: 'slash_water'
  },
  hinokami_enbu: {
    id: 'sk_sun_1',
    name: 'ヒノカミ神楽 円舞',
    katagaki: '日の呼吸',
    breathStyle: 'sun',
    bpCost: 16,
    power: 230,
    target: 'single',
    effectType: 'damage',
    description: '弧を描く猛烈な炎の刃で鬼を袈裟斬りにする。',
    animation: 'sun_burst'
  },
  hinokami_clear_sky: {
    id: 'sk_sun_2',
    name: 'ヒノカミ神楽 碧羅の天',
    katagaki: '日の呼吸',
    breathStyle: 'sun',
    bpCost: 28,
    power: 320,
    target: 'all',
    effectType: 'damage',
    description: '天に向かって青い炎の輪を描き、敵全体を焼き払う。',
    animation: 'sun_burst'
  },
  thunder_clap: {
    id: 'sk_thunder_1',
    name: '壱ノ型 霹靂一閃',
    katagaki: '雷の呼吸',
    breathStyle: 'thunder',
    bpCost: 6,
    power: 160,
    target: 'single',
    effectType: 'damage',
    description: '目にも止まらぬ電光石火の踏み込みで敵を一瞬で居合斬り。',
    animation: 'lightning'
  },
  thunder_god: {
    id: 'sk_thunder_7',
    name: '漆ノ型 火雷神',
    katagaki: '雷の呼吸',
    breathStyle: 'thunder',
    bpCost: 30,
    power: 350,
    target: 'single',
    effectType: 'damage',
    description: '我妻善逸が生み出した炎を纏う黄金の龍のような超神速の一撃。',
    animation: 'lightning'
  },
  beast_fangs: {
    id: 'sk_beast_5',
    name: '伍ノ牙 狂い裂き',
    katagaki: '獣の呼吸',
    breathStyle: 'beast',
    bpCost: 10,
    power: 175,
    target: 'all',
    effectType: 'damage',
    description: '二振りの刃を四方八方に乱れ斬り、敵陣を切り裂く。',
    animation: 'beast_fangs'
  },
  blood_burst: {
    id: 'sk_blood_nezuko',
    name: '血鬼術 爆血',
    katagaki: '血鬼術',
    breathStyle: 'blood',
    bpCost: 14,
    power: 210,
    target: 'all',
    effectType: 'damage',
    description: '自らの血液を燃え上がらせ、鬼にのみ激痛と特大の炎ダメージを与える。',
    animation: 'sun_burst'
  },
  flame_tiger: {
    id: 'sk_flame_5',
    name: '伍ノ型 炎虎',
    katagaki: '炎の呼吸',
    breathStyle: 'flame',
    bpCost: 18,
    power: 250,
    target: 'single',
    effectType: 'damage',
    description: '炎を纏う獰猛な虎の形となって突進する高威力の一撃。',
    animation: 'slash_flame'
  },
  flame_rengoku: {
    id: 'sk_flame_9',
    name: '玖ノ型 煉獄',
    katagaki: '炎の呼吸',
    breathStyle: 'flame',
    bpCost: 35,
    power: 380,
    target: 'all',
    effectType: 'damage',
    description: '心を燃やし大地を抉る轟音の突進！炎柱の奥義。',
    animation: 'slash_flame'
  },
  insect_dance: {
    id: 'sk_insect_1',
    name: '蝶ノ舞 戯れ',
    katagaki: '蟲の呼吸',
    bpCost: 12,
    power: 160,
    target: 'single',
    breathStyle: 'insect',
    effectType: 'damage',
    description: '蝶のように軽やかに舞い、藤の花の毒を仕込んだ針で急所を突く。',
    animation: 'butterfly'
  },
  mist_seventh: {
    id: 'sk_mist_7',
    name: '漆ノ型 朧',
    katagaki: '霞の呼吸',
    bpCost: 22,
    power: 270,
    target: 'single',
    breathStyle: 'mist',
    effectType: 'damage',
    description: '霞の揺らぎのように緩急をつけ、敵の視界から消え去り首を断つ。',
    animation: 'mist_cut'
  },
  sound_symphony: {
    id: 'sk_sound_5',
    name: '伍ノ型 鳴弦奏々',
    katagaki: '音の呼吸',
    bpCost: 20,
    power: 260,
    target: 'all',
    breathStyle: 'wind',
    effectType: 'damage',
    description: '炸裂玉と双刀を爆音とともに回転させ、周囲を一掃する。',
    animation: 'lightning'
  },
  love_claws: {
    id: 'sk_love_5',
    name: '伍ノ型 揺らめく恋情・乱れ爪',
    katagaki: '恋の呼吸',
    bpCost: 18,
    power: 230,
    target: 'all',
    breathStyle: 'love',
    effectType: 'damage',
    description: '新体操のようにしなる日輪刀を振り回し、広範囲を切り刻む。',
    animation: 'beast_fangs'
  },
  heal_herb: {
    id: 'sk_heal_basic',
    name: '全集中 常中・治癒',
    katagaki: '呼吸法',
    breathStyle: 'water',
    bpCost: 8,
    power: 120,
    target: 'ally_single',
    effectType: 'heal',
    description: '肺活量を高め、全身の血行を整えて傷を急速に癒す。',
    animation: 'heal_herb'
  },
  // Demon Blood Arts
  blood_arrow: {
    id: 'sk_b_arrow',
    name: '血鬼術 紅潔の矢',
    katagaki: '矢琶羽の血鬼術',
    breathStyle: 'blood',
    bpCost: 10,
    power: 140,
    target: 'single',
    effectType: 'damage',
    description: '不可視の矢印を飛ばし、敵を壁や地面に叩きつける。',
    animation: 'blood_dark'
  },
  blood_temari: {
    id: 'sk_b_temari',
    name: '血鬼術 毬遊び',
    katagaki: '朱紗丸の血鬼術',
    breathStyle: 'blood',
    bpCost: 12,
    power: 150,
    target: 'all',
    effectType: 'damage',
    description: '怪力で超高速の毬を放ち、敵全体を打ち砕く。',
    animation: 'blood_dark'
  },
  blood_drum: {
    id: 'sk_b_drum',
    name: '血鬼術 鼓打ち',
    katagaki: '響凱の血鬼術',
    breathStyle: 'blood',
    bpCost: 12,
    power: 160,
    target: 'all',
    effectType: 'damage',
    description: '体に埋め込まれた鼓を打ち鳴らし、爪のような斬撃と部屋の回転で襲う。',
    animation: 'beast_fangs'
  },
  blood_spider_threads: {
    id: 'sk_b_threads',
    name: '血鬼術 刻糸牢',
    katagaki: '累の血鬼術',
    breathStyle: 'blood',
    bpCost: 20,
    power: 240,
    target: 'all',
    effectType: 'damage',
    description: '日輪刀をもへし折る硬質な血の糸の網で敵全体を切り刻む。',
    animation: 'blood_dark'
  },
  blood_sleep: {
    id: 'sk_b_sleep',
    name: '血鬼術 強制昏倒催眠の囁き',
    katagaki: '魘夢の血鬼術',
    breathStyle: 'blood',
    bpCost: 22,
    power: 200,
    target: 'all',
    effectType: 'damage',
    description: '心地よい悪夢を見せて精神の核を破壊する。',
    animation: 'blood_dark'
  },
  blood_destructive_kill: {
    id: 'sk_b_compass',
    name: '血鬼術 破壊殺・羅針＆滅式',
    katagaki: '猗窩座の血鬼術',
    breathStyle: 'blood',
    bpCost: 28,
    power: 320,
    target: 'single',
    effectType: 'damage',
    description: '闘気を感知し、至高の武をもって放つ即死級の拳撃突進。',
    animation: 'sun_burst'
  },
  blood_flying_sickles: {
    id: 'sk_b_sickles',
    name: '血鬼術 飛び血鎌',
    katagaki: '妓夫太郎の血鬼術',
    breathStyle: 'blood',
    bpCost: 20,
    power: 120,
    target: 'all',
    effectType: 'damage',
    description: '猛毒を含んだ血の刃を自在に操る。',
    animation: 'beast_fangs'
  },
  blood_fish_pots: {
    id: 'sk_b_pots',
    name: '血鬼術 蛸壺地獄＆千本針',
    katagaki: '玉壺の血鬼術',
    breathStyle: 'blood',
    bpCost: 20,
    power: 125,
    target: 'all',
    effectType: 'damage',
    description: '壺から異形の触手と毒針を吹き出す。',
    animation: 'blood_dark'
  },
  blood_wooden_dragons: {
    id: 'sk_b_dragons',
    name: '血鬼術 無間業樹＆狂圧鳴波',
    katagaki: '半天狗の血鬼術',
    breathStyle: 'blood',
    bpCost: 24,
    power: 135,
    target: 'all',
    effectType: 'damage',
    description: '憎珀天が操る巨大な木竜と超音波で攻撃する。',
    animation: 'sun_burst'
  },
  blood_moon_slashes: {
    id: 'sk_b_moon',
    name: '月の呼吸 拾陸ノ型 月虹・片割れ月',
    katagaki: '黒死牟の血鬼術・呼吸',
    breathStyle: 'moon',
    bpCost: 28,
    power: 145,
    target: 'all',
    effectType: 'damage',
    description: '三日月の刃を降らせて敵を切り刻む。',
    animation: 'mist_cut'
  },
  blood_muzan_shockwave: {
    id: 'sk_b_muzan',
    name: '血鬼術 衝撃波・黒血枳棘',
    katagaki: '鬼舞辻無惨の始祖血鬼術',
    breathStyle: 'blood',
    bpCost: 30,
    power: 155,
    target: 'all',
    effectType: 'damage',
    description: '背中と両腕から放つ衝撃波で敵全体を攻撃する。',
    animation: 'blood_dark'
  },
  mob_scratch: {
    id: 'sk_mob_scratch',
    name: '鋭い爪のひっかき',
    katagaki: '鬼の爪撃',
    breathStyle: 'blood',
    bpCost: 2,
    power: 55,
    target: 'single',
    effectType: 'damage',
    description: '長く伸びた爪で容赦なく引き裂く。',
    animation: 'beast_fangs'
  },
  mob_bite: {
    id: 'sk_mob_bite',
    name: '飢餓の噛みつき',
    katagaki: '鬼の牙',
    breathStyle: 'blood',
    bpCost: 4,
    power: 75,
    target: 'single',
    effectType: 'damage',
    description: '人間の血肉を求めて激しく喰らいつく。',
    animation: 'beast_fangs'
  },
  mob_dark_roar: {
    id: 'sk_mob_roar',
    name: '威嚇の暗黒咆哮',
    katagaki: '異形の咆哮',
    breathStyle: 'blood',
    bpCost: 5,
    power: 90,
    target: 'all',
    effectType: 'damage',
    description: '夜の静寂を切り裂く不気味な咆哮で精神を威圧する。',
    animation: 'blood_dark'
  },
  demon_tanjiro_blood_sun: {
    id: 'sk_demon_tanjiro_sun',
    name: '血鬼・日天陽光弾',
    katagaki: '鬼の王・陽光克服',
    breathStyle: 'sun',
    bpCost: 25,
    power: 160,
    target: 'all',
    effectType: 'damage',
    description: '太陽の光を完全に克服した鬼の王の口から放たれる高熱の衝撃波弾。',
    animation: 'sun_burst'
  },
  demon_tanjiro_spine_whips: {
    id: 'sk_demon_tanjiro_whips',
    name: '背骨触手乱舞',
    katagaki: '鬼の王の異形化',
    breathStyle: 'blood',
    bpCost: 20,
    power: 150,
    target: 'all',
    effectType: 'damage',
    description: '背中から突き出した無数の骨の管と触手で全方位を無慈悲に薙ぎ払う。',
    animation: 'beast_fangs'
  }
};

// Canon main characters
const CANON_HEROES: Omit<Character, 'catalogNo'>[] = [
  {
    id: 'char_tanjiro',
    name: '竈門炭治郎',
    title: '日の呼吸の継承者',
    role: 'slayer',
    rank: '癸',
    breathStyle: 'water',
    level: 1,
    exp: 0,
    nextExp: 20,
    stats: { maxHp: 85, hp: 85, maxBp: 40, bp: 40, attack: 32, defense: 24, speed: 20, luck: 25 },
    skills: [SKILLS.water_surface_slash, SKILLS.water_wheel, SKILLS.water_flow, SKILLS.hinokami_enbu, SKILLS.hinokami_clear_sky],
    spriteConfig: {
      hairColor: '#4a1515',
      skinColor: '#fcd34d',
      eyeColor: '#7f1d1d',
      haoriColor: '#059669',
      haoriPattern: 'checker_green',
      hasSword: true,
      accentColor: '#ef4444'
    },
    lore: '心優しき少年。鬼となった妹・禰豆子を人間に戻すため、鬼殺隊の門を叩く。水と日の呼吸を操る。',
    isUnlocked: true
  },
  {
    id: 'char_nezuko',
    name: '竈門禰豆子',
    title: '人を喰わぬ鬼',
    role: 'support',
    rank: '一般隊士',
    breathStyle: 'blood',
    level: 1,
    exp: 0,
    nextExp: 20,
    stats: { maxHp: 95, hp: 95, maxBp: 35, bp: 35, attack: 34, defense: 28, speed: 22, luck: 30 },
    skills: [SKILLS.blood_burst, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#1c1917',
      skinColor: '#fef3c7',
      eyeColor: '#f43f5e',
      haoriColor: '#fb7185',
      haoriPattern: 'plain',
      accentColor: '#fbbf24'
    },
    lore: '鬼になりながらも人を守るために戦う炭治郎の妹。血鬼術「爆血」で鬼を灼き尽くす。',
    isUnlocked: true
  },
  {
    id: 'char_zenitsu',
    name: '我妻善逸',
    title: '雷光の一撃',
    role: 'slayer',
    rank: '癸',
    breathStyle: 'thunder',
    level: 2,
    exp: 0,
    nextExp: 30,
    stats: { maxHp: 75, hp: 75, maxBp: 45, bp: 45, attack: 38, defense: 18, speed: 38, luck: 28 },
    skills: [SKILLS.thunder_clap, SKILLS.thunder_god],
    spriteConfig: {
      hairColor: '#eab308',
      skinColor: '#fde68a',
      eyeColor: '#ca8a04',
      haoriColor: '#f59e0b',
      haoriPattern: 'triangle_yellow',
      hasSword: true,
      accentColor: '#ffffff'
    },
    lore: '極度の恐怖で眠りに落ちると真の力を発揮する。「雷の呼吸 壱ノ型」を極限まで研ぎ澄ました。',
    isUnlocked: true
  },
  {
    id: 'char_inosuke',
    name: '嘴平伊之助',
    title: '猪突猛進の野生児',
    role: 'slayer',
    rank: '癸',
    breathStyle: 'beast',
    level: 2,
    exp: 0,
    nextExp: 30,
    stats: { maxHp: 90, hp: 90, maxBp: 30, bp: 30, attack: 37, defense: 26, speed: 28, luck: 18 },
    skills: [SKILLS.beast_fangs, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#1e3a8a',
      skinColor: '#fed7aa',
      eyeColor: '#10b981',
      haoriColor: '#78716c',
      haoriPattern: 'plain',
      hasMask: 'boar',
      hasSword: true,
      accentColor: '#3b82f6'
    },
    lore: '山育ちで並外れた触覚を持つ二刀流の剣士。自流の「獣の呼吸」で猪突猛進に突き進む。',
    isUnlocked: true
  },
  {
    id: 'char_giyu',
    name: '冨岡義勇',
    title: '水柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'water',
    level: 15,
    exp: 0,
    nextExp: 200,
    stats: { maxHp: 160, hp: 160, maxBp: 75, bp: 75, attack: 68, defense: 55, speed: 45, luck: 30 },
    skills: [SKILLS.water_surface_slash, SKILLS.water_wheel, SKILLS.water_dead_calm],
    spriteConfig: {
      hairColor: '#0f172a',
      skinColor: '#fed7aa',
      eyeColor: '#2563eb',
      haoriColor: '#b91c1c',
      haoriPattern: 'split_red_green',
      hasSword: true,
      accentColor: '#10b981'
    },
    lore: '炭治郎と禰豆子を鬼殺隊へと導いた水柱。独自の型「拾壱ノ型 凪」であらゆる攻撃を無力化する。',
    isUnlocked: true
  },
  {
    id: 'char_shinobu',
    name: '胡蝶しのぶ',
    title: '蟲柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'insect',
    level: 15,
    exp: 0,
    nextExp: 200,
    stats: { maxHp: 125, hp: 125, maxBp: 90, bp: 90, attack: 52, defense: 38, speed: 58, luck: 40 },
    skills: [SKILLS.insect_dance, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#3b0764',
      skinColor: '#fef3c7',
      eyeColor: '#a855f7',
      haoriColor: '#e0e7ff',
      haoriPattern: 'butterfly_wing',
      hasSword: true,
      accentColor: '#9333ea'
    },
    lore: '鬼の首を斬れない代わりに藤の花から精製した毒を突き刺して倒す薬学の天才。',
    isUnlocked: true
  },
  {
    id: 'char_rengoku',
    name: '煉獄杏寿郎',
    title: '炎柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'flame',
    level: 20,
    exp: 0,
    nextExp: 350,
    stats: { maxHp: 210, hp: 210, maxBp: 95, bp: 95, attack: 88, defense: 68, speed: 52, luck: 35 },
    skills: [SKILLS.flame_tiger, SKILLS.flame_rengoku, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#f59e0b',
      skinColor: '#fed7aa',
      eyeColor: '#dc2626',
      haoriColor: '#fafaf9',
      haoriPattern: 'flame_edge',
      hasSword: true,
      accentColor: '#b91c1c'
    },
    lore: '「心を燃やせ」を信条とする炎柱。無限列車にて乗客と後輩全員を守り抜き、猗窩座と激闘を繰り広げた。',
    isUnlocked: false
  },
  {
    id: 'char_tengen',
    name: '宇髄天元',
    title: '音柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'wind',
    level: 22,
    exp: 0,
    nextExp: 400,
    stats: { maxHp: 220, hp: 220, maxBp: 90, bp: 90, attack: 86, defense: 70, speed: 64, luck: 32 },
    skills: [SKILLS.sound_symphony, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#cbd5e1',
      skinColor: '#fde68a',
      eyeColor: '#be123c',
      haoriColor: '#334155',
      haoriPattern: 'solid_black',
      hasSword: true,
      accentColor: '#e11d48'
    },
    lore: '派手を司る元忍の音柱。敵の攻撃動作を音の譜面として読み解き反撃する「譜面」を完成させる。',
    isUnlocked: false
  },
  {
    id: 'char_muichiro',
    name: '時透無一郎',
    title: '霞柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'mist',
    level: 32,
    exp: 0,
    nextExp: 500,
    stats: { maxHp: 320, hp: 320, maxBp: 150, bp: 150, attack: 118, defense: 82, speed: 88, luck: 42 },
    skills: [SKILLS.mist_seventh, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#0f172a',
      skinColor: '#fef3c7',
      eyeColor: '#06b6d4',
      haoriColor: '#1e293b',
      haoriPattern: 'solid_black',
      hasSword: true,
      accentColor: '#22d3ee'
    },
    lore: '刀を握ってわずか2ヶ月で柱となった天才少年。霞の呼吸の独自型「朧」で上弦の伍・玉壺を単独撃破。',
    isUnlocked: false
  },
  {
    id: 'char_mitsuri',
    name: '甘露寺蜜璃',
    title: '恋柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'love',
    level: 32,
    exp: 0,
    nextExp: 500,
    stats: { maxHp: 360, hp: 360, maxBp: 140, bp: 140, attack: 115, defense: 88, speed: 78, luck: 40 },
    skills: [SKILLS.love_claws, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#f472b6',
      skinColor: '#fef3c7',
      eyeColor: '#10b981',
      haoriColor: '#fafaf9',
      haoriPattern: 'solid_white',
      hasSword: true,
      accentColor: '#4ade80'
    },
    lore: '常人の8倍の筋肉密度を持つ恋柱。新体操のようにしなる極薄の刀で華麗かつ豪快に鬼を切り刻む。',
    isUnlocked: false
  },
  {
    id: 'char_gyomei',
    name: '悲鳴嶼行冥',
    title: '岩柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'stone',
    level: 38,
    exp: 0,
    nextExp: 700,
    stats: { maxHp: 460, hp: 460, maxBp: 180, bp: 180, attack: 142, defense: 115, speed: 65, luck: 35 },
    skills: [SKILLS.beast_fangs, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#1c1917',
      skinColor: '#fed7aa',
      eyeColor: '#e2e8f0',
      haoriColor: '#65a30d',
      haoriPattern: 'solid_white',
      hasSword: true,
      accentColor: '#84cc16'
    },
    lore: '鬼殺隊最強と謳われる岩柱。鎖で繋がれた鉄球と斧を怪力で操り、数々の死線を越えてきた。',
    isUnlocked: false
  },
  {
    id: 'char_sanemi',
    name: '不死川実弥',
    title: '風柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'wind',
    level: 36,
    exp: 0,
    nextExp: 600,
    stats: { maxHp: 390, hp: 390, maxBp: 150, bp: 150, attack: 132, defense: 92, speed: 85, luck: 30 },
    skills: [SKILLS.beast_fangs, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#e2e8f0',
      skinColor: '#fde68a',
      eyeColor: '#475569',
      haoriColor: '#ffffff',
      haoriPattern: 'solid_white',
      hasSword: true,
      accentColor: '#10b981'
    },
    lore: '稀血中の稀血を持つ風柱。鬼を酩酊させる特殊な血と狂乱の連撃で鬼を圧倒する。',
    isUnlocked: false
  },
  {
    id: 'char_obanai',
    name: '伊黒小芭内',
    title: '蛇柱',
    role: 'slayer',
    rank: '柱',
    breathStyle: 'serpent',
    level: 36,
    exp: 0,
    nextExp: 600,
    stats: { maxHp: 350, hp: 350, maxBp: 155, bp: 155, attack: 126, defense: 88, speed: 88, luck: 38 },
    skills: [SKILLS.water_flow, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#0f172a',
      skinColor: '#fef3c7',
      eyeColor: '#eab308',
      haoriColor: '#000000',
      haoriPattern: 'striped_purple',
      hasSword: true,
      accentColor: '#06b6d4'
    },
    lore: 'うねる波状の刀身と鏑丸との連携で、僅かな隙間をも縫う太刀筋を放つ蛇柱。',
    isUnlocked: false
  },
  {
    id: 'char_kanao',
    name: '栗花落カナヲ',
    title: '花の呼吸の継承者',
    role: 'slayer',
    rank: '丁',
    breathStyle: 'flower',
    level: 12,
    exp: 0,
    nextExp: 150,
    stats: { maxHp: 130, hp: 130, maxBp: 70, bp: 70, attack: 56, defense: 42, speed: 54, luck: 35 },
    skills: [SKILLS.water_wheel, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#1e293b',
      skinColor: '#fef3c7',
      eyeColor: '#ec4899',
      haoriColor: '#ffffff',
      haoriPattern: 'solid_white',
      hasSword: true,
      accentColor: '#f472b6'
    },
    lore: '胡蝶姉妹の継子。優れた動体視力を持ち、花の呼吸を美しく舞うように繰り出す。',
    isUnlocked: true
  },
  {
    id: 'char_genya',
    name: '不死川玄弥',
    title: '鬼喰いの戦士',
    role: 'slayer',
    rank: '丁',
    breathStyle: 'none',
    level: 10,
    exp: 0,
    nextExp: 120,
    stats: { maxHp: 150, hp: 150, maxBp: 40, bp: 40, attack: 58, defense: 48, speed: 30, luck: 22 },
    skills: [SKILLS.beast_fangs, SKILLS.heal_herb],
    spriteConfig: {
      hairColor: '#0f172a',
      skinColor: '#fed7aa',
      eyeColor: '#334155',
      haoriColor: '#7c3aed',
      haoriPattern: 'plain',
      hasSword: true,
      accentColor: '#8b5cf6'
    },
    lore: '呼吸は使えないが、鬼の肉を喰らうことで一時的に鬼の怪力と再生能力を得る特異体質。銃も用いる。',
    isUnlocked: true
  }
];

// Canon named demons (No generic/nameless zako demons)
const CANON_DEMONS: Omit<Character, 'catalogNo'>[] = [
  {
    id: 'demon_temple',
    name: 'お堂の鬼',
    title: '狭霧山麓の夜鬼',
    role: 'demon',
    rank: '一般鬼',
    breathStyle: 'blood',
    level: 2,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 120, hp: 120, maxBp: 30, bp: 30, attack: 28, defense: 16, speed: 14, luck: 10 },
    skills: [SKILLS.beast_fangs],
    spriteConfig: { hairColor: '#1e293b', skinColor: '#94a3b8', eyeColor: '#ef4444', haoriColor: '#334155', haoriPattern: 'plain', hasHorn: false, accentColor: '#dc2626' },
    lore: '狭霧山へ向かう炭治郎が山中のお堂で遭遇した鬼。斧で頸を断たれても活動する異形の生命力を見せた。',
    isUnlocked: false
  },
  {
    id: 'demon_hand',
    name: '手鬼',
    title: '藤襲山の異形鬼',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 5,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 220, hp: 220, maxBp: 50, bp: 50, attack: 36, defense: 22, speed: 16, luck: 10 },
    skills: [SKILLS.blood_drum],
    spriteConfig: { hairColor: '#064e3b', skinColor: '#047857', eyeColor: '#facc15', haoriColor: '#065f46', haoriPattern: 'demon_mark', hasHorn: true, accentColor: '#dc2626' },
    lore: '鱗滝に捕らえられ最終選別の藤襲山に封じられた鬼。鱗滝の弟子たちを50年にわたり喰らってきた。',
    isUnlocked: false
  },
  {
    id: 'demon_swamp',
    name: '沼の鬼（三身一体）',
    title: '北西の町の誘拐鬼',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 7,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 280, hp: 280, maxBp: 60, bp: 60, attack: 42, defense: 25, speed: 22, luck: 12 },
    skills: [SKILLS.blood_arrow],
    spriteConfig: { hairColor: '#0f172a', skinColor: '#64748b', eyeColor: '#f59e0b', haoriColor: '#1e293b', haoriPattern: 'plain', hasHorn: true, accentColor: '#0284c7' },
    lore: '十六歳の少女ばかりを狙って地中や壁の沼地に引きずり込む鬼。三体に分裂して連係攻撃を行う。',
    isUnlocked: false
  },
  {
    id: 'demon_yahaba_susamaru',
    name: '朱紗丸＆矢琶羽',
    title: '浅草の刺客',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 9,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 380, hp: 380, maxBp: 80, bp: 80, attack: 48, defense: 30, speed: 28, luck: 15 },
    skills: [SKILLS.blood_temari, SKILLS.blood_arrow],
    spriteConfig: { hairColor: '#b91c1c', skinColor: '#fed7aa', eyeColor: '#f59e0b', haoriColor: '#7f1d1d', haoriPattern: 'spotted', hasHorn: false, accentColor: '#ea580c' },
    lore: '無惨の命を受けて浅草で炭治郎らを急襲した二人組。矢印と超速の毬の連動攻撃を繰り出す。',
    isUnlocked: false
  },
  {
    id: 'demon_susamaru',
    name: '朱紗丸',
    title: '毬の鬼・腕六本形態',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 10,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 320, hp: 320, maxBp: 70, bp: 70, attack: 46, defense: 28, speed: 26, luck: 14 },
    skills: [SKILLS.blood_temari],
    spriteConfig: { hairColor: '#ea580c', skinColor: '#fed7aa', eyeColor: '#f59e0b', haoriColor: '#c2410c', haoriPattern: 'spotted', hasHorn: false, accentColor: '#f97316' },
    lore: '六本の腕から超高速の毬を放ち周囲を破壊し尽くす。自らを十二鬼月と信じ込んでいた。',
    isUnlocked: false
  },
  {
    id: 'demon_yahaba',
    name: '矢琶羽',
    title: '紅潔の矢の鬼',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 10,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 310, hp: 310, maxBp: 75, bp: 75, attack: 47, defense: 26, speed: 30, luck: 15 },
    skills: [SKILLS.blood_arrow],
    spriteConfig: { hairColor: '#1e293b', skinColor: '#e2e8f0', eyeColor: '#eab308', haoriColor: '#334155', haoriPattern: 'plain', hasHorn: false, accentColor: '#ca8a04' },
    lore: '掌の眼球から放たれる目に見えぬ矢印で相手を吹き飛ばす潔癖症の鬼。',
    isUnlocked: false
  },
  {
    id: 'demon_kyogai',
    name: '響凱',
    title: '元下弦の陸・鼓の鬼',
    role: 'demon',
    rank: '下弦',
    breathStyle: 'blood',
    level: 13,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 520, hp: 520, maxBp: 100, bp: 100, attack: 58, defense: 38, speed: 30, luck: 15 },
    skills: [SKILLS.blood_drum],
    spriteConfig: { hairColor: '#1c1917', skinColor: '#e2e8f0', eyeColor: '#dc2626', haoriColor: '#78350f', haoriPattern: 'plain', hasHorn: false, accentColor: '#d97706' },
    lore: '体に埋め込まれた鼓を打ち鳴らし部屋を回転させ爪の斬撃を放つ。稀血の少年を狙い鼓屋敷に潜む。',
    isUnlocked: false
  },
  {
    id: 'demon_tongue',
    name: '舌の鬼',
    title: '鼓屋敷の徘徊鬼',
    role: 'demon',
    rank: '一般鬼',
    breathStyle: 'blood',
    level: 11,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 290, hp: 290, maxBp: 60, bp: 60, attack: 44, defense: 26, speed: 32, luck: 10 },
    skills: [SKILLS.beast_fangs],
    spriteConfig: { hairColor: '#172554', skinColor: '#cbd5e1', eyeColor: '#ef4444', haoriColor: '#1e1b4b', haoriPattern: 'demon_mark', hasHorn: false, accentColor: '#e11d48' },
    lore: '異様に長い舌を持ち、獲物を壁や天井から急襲する鬼。眠った善逸の霹靂一閃で一刀両断された。',
    isUnlocked: false
  },
  {
    id: 'demon_spider_mother',
    name: '蜘蛛の鬼（母）',
    title: '那田蜘蛛山の傀儡師',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 15,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 440, hp: 440, maxBp: 90, bp: 90, attack: 52, defense: 32, speed: 36, luck: 18 },
    skills: [SKILLS.blood_spider_threads],
    spriteConfig: { hairColor: '#f8fafc', skinColor: '#f1f5f9', eyeColor: '#dc2626', haoriColor: '#ffffff', haoriPattern: 'demon_mark', hasHorn: false, accentColor: '#38bdf8' },
    lore: '極細の糸で鬼殺隊士の体を人形のように操る母役の鬼。炭治郎の慈悲の剣「干天の慈雨」を受け安らかに逝く。',
    isUnlocked: false
  },
  {
    id: 'demon_spider_father',
    name: '蜘蛛の鬼（父）',
    title: '那田蜘蛛山の怪力巨漢',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 16,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 620, hp: 620, maxBp: 80, bp: 80, attack: 68, defense: 54, speed: 20, luck: 12 },
    skills: [SKILLS.beast_fangs],
    spriteConfig: { hairColor: '#0f172a', skinColor: '#475569', eyeColor: '#ef4444', haoriColor: '#18181b', haoriPattern: 'plain', hasHorn: true, accentColor: '#dc2626' },
    lore: '蜘蛛の頭部と鋼のような筋肉を持つ巨漢の鬼。脱皮によって更に巨大化し伊之助を圧倒した。',
    isUnlocked: false
  },
  {
    id: 'demon_spider_brother',
    name: '蜘蛛の鬼（兄）',
    title: '人面蜘蛛の毒針使い',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 15,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 460, hp: 460, maxBp: 95, bp: 95, attack: 55, defense: 34, speed: 40, luck: 15 },
    skills: [SKILLS.blood_arrow],
    spriteConfig: { hairColor: '#334155', skinColor: '#94a3b8', eyeColor: '#eab308', haoriColor: '#0f172a', haoriPattern: 'spotted', hasHorn: false, accentColor: '#a855f7' },
    lore: '人間を人面蜘蛛へと変貌させる毒を操る鬼。善逸を毒で瀕死に追い込むも、神速の六連撃に散る。',
    isUnlocked: false
  },
  {
    id: 'demon_spider_sister',
    name: '蜘蛛の鬼（姉）',
    title: '溶解繭の絹糸使い',
    role: 'demon',
    rank: '異形鬼',
    breathStyle: 'blood',
    level: 15,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 450, hp: 450, maxBp: 90, bp: 90, attack: 50, defense: 32, speed: 38, luck: 16 },
    skills: [SKILLS.blood_spider_threads],
    spriteConfig: { hairColor: '#f8fafc', skinColor: '#f1f5f9', eyeColor: '#f43f5e', haoriColor: '#ffffff', haoriPattern: 'plain', hasHorn: false, accentColor: '#ec4899' },
    lore: '人間を糸の繭に閉じ込めて酸で溶かし喰らう姉役の鬼。胡蝶しのぶの藤の花の毒によって倒される。',
    isUnlocked: false
  },
  {
    id: 'demon_rui',
    name: '下弦の伍・累',
    title: '那田蜘蛛山の主',
    role: 'demon',
    rank: '下弦',
    breathStyle: 'blood',
    level: 18,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 750, hp: 750, maxBp: 150, bp: 150, attack: 72, defense: 50, speed: 42, luck: 20 },
    skills: [SKILLS.blood_spider_threads],
    spriteConfig: { hairColor: '#f8fafc', skinColor: '#f1f5f9', eyeColor: '#dc2626', haoriColor: '#ffffff', haoriPattern: 'demon_mark', hasHorn: false, accentColor: '#b91c1c' },
    lore: '家族の絆を求めて偽りの蜘蛛家族を作っていた十二鬼月。鋼鉄以上の強度を誇る血の糸で敵を切り刻む。',
    isUnlocked: false
  },
  {
    id: 'demon_enmu_akaza',
    name: '魘夢 ＆ 猗窩座',
    title: '無限列車の悪夢＆上弦の参',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 24,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1100, hp: 1100, maxBp: 220, bp: 220, attack: 96, defense: 68, speed: 60, luck: 25 },
    skills: [SKILLS.blood_sleep, SKILLS.blood_destructive_kill],
    spriteConfig: { hairColor: '#ec4899', skinColor: '#cbd5e1', eyeColor: '#e11d48', haoriColor: '#1e1b4b', haoriPattern: 'demon_mark', hasHorn: false, accentColor: '#06b6d4' },
    lore: '夢を操る下弦の壱・魘夢を退けた後、突如飛来した至高の武を求める上弦の参・猗窩座。煉獄と激突。',
    isUnlocked: false
  },
  {
    id: 'demon_enmu',
    name: '下弦の壱・魘夢',
    title: '夢幻の支配者',
    role: 'demon',
    rank: '下弦',
    breathStyle: 'blood',
    level: 22,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 850, hp: 850, maxBp: 180, bp: 180, attack: 82, defense: 58, speed: 52, luck: 24 },
    skills: [SKILLS.blood_sleep],
    spriteConfig: { hairColor: '#ec4899', skinColor: '#f1f5f9', eyeColor: '#06b6d4', haoriColor: '#1e1b4b', haoriPattern: 'plain', hasHorn: false, accentColor: '#38bdf8' },
    lore: '列車そのものと融合し乗客200人を人質に取った下弦の壱。甘美な夢を見せつつ精神の核を狙う。',
    isUnlocked: false
  },
  {
    id: 'demon_akaza',
    name: '上弦の参・猗窩座',
    title: '破壊殺の武人',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 28,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1350, hp: 1350, maxBp: 280, bp: 280, attack: 118, defense: 84, speed: 78, luck: 30 },
    skills: [SKILLS.blood_destructive_kill],
    spriteConfig: { hairColor: '#f43f5e', skinColor: '#fed7aa', eyeColor: '#eab308', haoriColor: '#881337', haoriPattern: 'demon_mark', hasHorn: false, accentColor: '#06b6d4' },
    lore: '至高の領域を目指し百数十年鍛錬を重ねた武闘派の上弦。闘気を感知する術式展開「羅針」を操る。',
    isUnlocked: false
  },
  {
    id: 'demon_daki_gyutaro',
    name: '上弦の陸・堕姫＆妓夫太郎',
    title: '吉原遊郭の兄妹鬼',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 30,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1450, hp: 1450, maxBp: 260, bp: 260, attack: 112, defense: 78, speed: 70, luck: 25 },
    skills: [SKILLS.blood_flying_sickles],
    spriteConfig: { hairColor: '#15803d', skinColor: '#cbd5e1', eyeColor: '#dc2626', haoriColor: '#831843', haoriPattern: 'plain', hasHorn: false, accentColor: '#16a34a' },
    lore: '吉原遊郭に百年間君臨する兄妹鬼。二人同時に首を切り落とさねば絶命しない強敵。猛毒の血鎌を操る。',
    isUnlocked: false
  },
  {
    id: 'demon_daki',
    name: '上弦の陸・堕姫',
    title: '美しき帯の鬼',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 27,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1100, hp: 1100, maxBp: 220, bp: 220, attack: 98, defense: 68, speed: 65, luck: 22 },
    skills: [SKILLS.blood_arrow],
    spriteConfig: { hairColor: '#cbd5e1', skinColor: '#fed7aa', eyeColor: '#16a34a', haoriColor: '#9d174d', haoriPattern: 'plain', hasHorn: false, accentColor: '#f43f5e' },
    lore: '花魁「蕨姫」として遊郭に潜み、伸縮自在の鋭利な八重帯で敵を切り刻む兄思いの鬼。',
    isUnlocked: false
  },
  {
    id: 'demon_gyutaro',
    name: '上弦の陸・妓夫太郎',
    title: '猛毒血鎌の兄鬼',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 30,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1350, hp: 1350, maxBp: 250, bp: 250, attack: 115, defense: 80, speed: 72, luck: 26 },
    skills: [SKILLS.blood_flying_sickles],
    spriteConfig: { hairColor: '#15803d', skinColor: '#64748b', eyeColor: '#dc2626', haoriColor: '#1c1917', haoriPattern: 'demon_mark', hasHorn: false, accentColor: '#22c55e' },
    lore: '堕姫の背中の中から現れる真の上弦の陸。致死性の猛毒を帯びた飛び血鎌で敵を滅殺する。',
    isUnlocked: false
  },
  {
    id: 'demon_gyokko_hantengu',
    name: '上弦の肆・半天狗 ＆ 上弦の伍・玉壺',
    title: '刀鍛冶の里襲撃組',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 36,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 880, hp: 880, maxBp: 200, bp: 200, attack: 64, defense: 46, speed: 60, luck: 20 },
    skills: [SKILLS.blood_fish_pots, SKILLS.blood_wooden_dragons],
    spriteConfig: { hairColor: '#334155', skinColor: '#94a3b8', eyeColor: '#eab308', haoriColor: '#475569', haoriPattern: 'spotted', hasHorn: true, accentColor: '#3b82f6' },
    lore: '刀鍛冶の隠れ里を滅ぼすべく現れた二体の上弦。分裂と合体を繰り返す憎珀天と奇怪な壺の芸術鬼。',
    isUnlocked: false
  },
  {
    id: 'demon_gyokko',
    name: '上弦の伍・玉壺',
    title: '壺の異形芸術家',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 34,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 780, hp: 780, maxBp: 180, bp: 180, attack: 60, defense: 42, speed: 56, luck: 18 },
    skills: [SKILLS.blood_fish_pots],
    spriteConfig: { hairColor: '#e2e8f0', skinColor: '#cbd5e1', eyeColor: '#eab308', haoriColor: '#475569', haoriPattern: 'spotted', hasHorn: false, accentColor: '#06b6d4' },
    lore: '頭部と口が入れ替わった奇怪な姿の上弦。壺の間を神出鬼没に転移し毒針魚や蛸壺で蹂躙する。',
    isUnlocked: false
  },
  {
    id: 'demon_zohakuten',
    name: '上弦の肆・憎珀天',
    title: '喜怒哀楽の合体鬼',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 37,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 920, hp: 920, maxBp: 220, bp: 220, attack: 66, defense: 48, speed: 62, luck: 22 },
    skills: [SKILLS.blood_wooden_dragons],
    spriteConfig: { hairColor: '#1c1917', skinColor: '#cbd5e1', eyeColor: '#ea580c', haoriColor: '#78350f', haoriPattern: 'demon_mark', hasHorn: true, accentColor: '#f59e0b' },
    lore: '積怒が他の喜怒哀楽鬼を吸収して顕現した少年姿の上弦。背の雷鼓を打ち鳴らし巨大な木竜を操る。',
    isUnlocked: false
  },
  {
    id: 'demon_doma',
    name: '上弦の弐・童磨',
    title: '万世極楽教の教祖',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 40,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1020, hp: 1020, maxBp: 240, bp: 240, attack: 68, defense: 50, speed: 64, luck: 25 },
    skills: [SKILLS.blood_fish_pots],
    spriteConfig: { hairColor: '#fef08a', skinColor: '#f8fafc', eyeColor: '#38bdf8', haoriColor: '#991b1b', haoriPattern: 'spotted', hasHorn: false, accentColor: '#f43f5e' },
    lore: '感情を持たぬ万世極楽教の教祖。吸い込むと肺が壊死する猛烈な冷気と氷の菩薩を生み出す。',
    isUnlocked: false
  },
  {
    id: 'demon_kokushibo',
    name: '上弦の壱・黒死牟',
    title: '月の呼吸の武士',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'moon',
    level: 43,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1150, hp: 1150, maxBp: 260, bp: 260, attack: 72, defense: 52, speed: 66, luck: 26 },
    skills: [SKILLS.blood_moon_slashes],
    spriteConfig: { hairColor: '#450a0a', skinColor: '#e2e8f0', eyeColor: '#dc2626', haoriColor: '#581c87', haoriPattern: 'checker_green', hasHorn: false, accentColor: '#9333ea' },
    lore: '四百年以上無惨に仕える上弦の頂点。六つの眼を持ち、自らの肉体から生じた刀で月の呼吸を操る。',
    isUnlocked: false
  },
  {
    id: 'demon_nakime',
    name: '新・上弦の肆・鳴女',
    title: '無限城の琵琶鬼',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'blood',
    level: 35,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 800, hp: 800, maxBp: 200, bp: 200, attack: 58, defense: 44, speed: 56, luck: 20 },
    skills: [SKILLS.blood_drum],
    spriteConfig: { hairColor: '#09090b', skinColor: '#cbd5e1', eyeColor: '#eab308', haoriColor: '#27272a', haoriPattern: 'plain', hasHorn: false, accentColor: '#ca8a04' },
    lore: '前髪で単眼を隠した琵琶弾きの鬼。無限城の空間構造を自在に書き換え隊士たちを分断する。',
    isUnlocked: false
  },
  {
    id: 'demon_kaigaku',
    name: '新・上弦の陸・獪岳（鬼）',
    title: '黒雷を纏う裏切り者',
    role: 'demon',
    rank: '上弦',
    breathStyle: 'thunder',
    level: 32,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 750, hp: 750, maxBp: 180, bp: 180, attack: 60, defense: 42, speed: 62, luck: 18 },
    skills: [SKILLS.thunder_god],
    spriteConfig: { hairColor: '#09090b', skinColor: '#94a3b8', eyeColor: '#06b6d4', haoriColor: '#1e293b', haoriPattern: 'plain', hasHorn: false, accentColor: '#0891b2' },
    lore: '善逸の兄弟子でありながら生き汚く鬼へ寝返った男。黒い雷で肉体を亀裂させ焼き焦がす。',
    isUnlocked: false
  },
  {
    id: 'demon_muzan_final',
    name: '鬼舞辻無惨（始祖）＆ 黒死牟',
    title: '鬼の始祖・千年を生きた夜の王',
    role: 'demon',
    rank: '鬼の始祖',
    breathStyle: 'blood',
    level: 45,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1250, hp: 1250, maxBp: 300, bp: 300, attack: 74, defense: 54, speed: 68, luck: 28 },
    skills: [SKILLS.blood_moon_slashes, SKILLS.blood_muzan_shockwave],
    spriteConfig: { hairColor: '#09090b', skinColor: '#f1f5f9', eyeColor: '#dc2626', haoriColor: '#18181b', haoriPattern: 'solid_black', hasHorn: true, accentColor: '#991b1b' },
    lore: '千年以上生き続ける全ての鬼の始祖。無限城にて鬼殺隊全戦力と激突。圧倒的な細胞破壊と触手で蹂躙する。',
    isUnlocked: false
  },
  {
    id: 'demon_tanjiro',
    name: '鬼化・竈門炭治郎',
    title: '鬼の王・陽光を克服せし最凶の鬼',
    role: 'demon',
    rank: '鬼の始祖',
    breathStyle: 'sun',
    level: 50,
    exp: 0,
    nextExp: 0,
    stats: { maxHp: 1500, hp: 1500, maxBp: 350, bp: 350, attack: 85, defense: 60, speed: 75, luck: 35 },
    skills: [SKILLS.demon_tanjiro_blood_sun, SKILLS.demon_tanjiro_spine_whips, SKILLS.hinokami_clear_sky],
    spriteConfig: {
      hairColor: '#3b0764',
      skinColor: '#cbd5e1',
      eyeColor: '#ef4444',
      haoriColor: '#059669',
      haoriPattern: 'checker_green',
      hasHorn: true,
      accentColor: '#dc2626'
    },
    lore: '無惨の全ての血と力、想いを注ぎ込まれて鬼の王へと変貌した炭治郎。陽の光を克服し、日輪刀の斬撃さえ通用しない。仲間たちの命懸けの呼びかけと人間に戻す薬だけが救いとなる。',
    isUnlocked: false
  }
];

// Helper to generate the full 500 characters
export function generateCharacterCatalog(): Character[] {
  const catalog: Character[] = [];
  let currentNo = 1;

  // 1. Add Canon Heroes (15 characters)
  for (const hero of CANON_HEROES) {
    catalog.push({
      ...hero,
      catalogNo: currentNo++,
    });
  }

  // 2. Add Canon Demons / Bosses (8 characters)
  for (const demon of CANON_DEMONS) {
    catalog.push({
      ...demon,
      catalogNo: currentNo++,
    });
  }

  // 3. Named trainee, swordsmiths, kakushi, family, kunoichi, and mentors
  const SPECIAL_MEMBERS = [
    { id: 'char_urokodaki', name: '鱗滝左近次', title: '元水柱・育手', breath: 'water', rank: '育手', haori: 'split_red_green', color: '#0284c7' },
    { id: 'char_sabito', name: '錆兎', title: '水の呼吸の修業者', breath: 'water', rank: '一般隊士', haori: 'plain', color: '#f97316' },
    { id: 'char_makomo', name: '真菰', title: '可憐なる水の修業者', breath: 'water', rank: '一般隊士', haori: 'plain', color: '#06b6d4' },
    { id: 'char_haganezuka', name: '鋼鐵塚蛍', title: '日輪刀研磨職人', breath: 'none', rank: '刀鍛冶', haori: 'plain', color: '#b91c1c' },
    { id: 'char_kanamori', name: '鉄穴森鋼蔵', title: '穏やかな刀鍛冶', breath: 'none', rank: '刀鍛冶', haori: 'plain', color: '#64748b' },
    { id: 'char_kotetsu', name: '小鉄', title: '縁壱零式の管理人', breath: 'none', rank: '刀鍛冶', haori: 'plain', color: '#eab308' },
    { id: 'char_tecchin', name: '鉄地河原鉄珍', title: '刀鍛冶の里長', breath: 'none', rank: '刀鍛冶', haori: 'plain', color: '#d97706' },
    { id: 'char_aoi', name: '神崎アオイ', title: '蝶屋敷の医療隊士', breath: 'water', rank: '一般隊士', haori: 'plain', color: '#3b82f6' },
    { id: 'char_naho', name: '高田なほ', title: '蝶屋敷の看護三人娘', breath: 'none', rank: '隠', haori: 'plain', color: '#ec4899' },
    { id: 'char_kiyo', name: '寺内きよ', title: '蝶屋敷の看護三人娘', breath: 'none', rank: '隠', haori: 'plain', color: '#f43f5e' },
    { id: 'char_sumi', name: '中原すみ', title: '蝶屋敷の看護三人娘', breath: 'none', rank: '隠', haori: 'plain', color: '#fb7185' },
    { id: 'char_murata', name: '村田', title: '強運の先輩隊士', breath: 'water', rank: '庚', haori: 'plain', color: '#0ea5e9' },
    { id: 'char_ozaki', name: '尾崎', title: '蜘蛛山を生き抜いた隊士', breath: 'flower', rank: '辛', haori: 'plain', color: '#a855f7' },
    { id: 'char_takeuchi', name: '竹内', title: '無限城を駆ける隊士', breath: 'water', rank: '己', haori: 'plain', color: '#0284c7' },
    { id: 'char_maeda', name: '前田まさお', title: 'ゲスメガネ・隊服縫製係', breath: 'none', rank: '隠', haori: 'solid_black', color: '#334155' },
    { id: 'char_goto', name: '後藤', title: '義理堅き隠の隊士', breath: 'none', rank: '隠', haori: 'solid_black', color: '#475569' },
    { id: 'char_chachamaru', name: '茶々丸', title: '血を運ぶ賢き三毛猫', breath: 'none', rank: '隠', haori: 'plain', color: '#ea580c' },
    { id: 'char_matsuemon', name: '鎹鴉・天王寺松右衛門', title: '炭治郎の鎹鴉', breath: 'none', rank: '隠', haori: 'solid_black', color: '#1e293b' },
    { id: 'char_chuntaro', name: '雀・チュン太郎', title: '善逸の忠実な雀', breath: 'none', rank: '隠', haori: 'plain', color: '#f59e0b' },
    { id: 'char_kaburamaru', name: '鏑丸', title: '伊黒の相棒白蛇', breath: 'serpent', rank: '隠', haori: 'solid_white', color: '#cbd5e1' },
    { id: 'char_kagaya', name: '産屋敷耀哉', title: '鬼殺隊第97代当主', breath: 'none', rank: '柱', haori: 'solid_white', color: '#6366f1' },
    { id: 'char_amane', name: '産屋敷あまね', title: '当主の妻・慈愛の守り手', breath: 'none', rank: '柱', haori: 'solid_white', color: '#818cf8' },
    { id: 'char_kiriya', name: '産屋敷輝利哉', title: '鬼殺隊第98代当主', breath: 'none', rank: '柱', haori: 'solid_white', color: '#4f46e5' },
    { id: 'char_kanata', name: '産屋敷かなた', title: '最終選別の案内役', breath: 'none', rank: '隠', haori: 'solid_white', color: '#a855f7' },
    { id: 'char_kuina', name: '産屋敷くいな', title: '無限城指揮補佐', breath: 'none', rank: '隠', haori: 'solid_white', color: '#6366f1' },
    { id: 'char_nichika', name: '産屋敷にちか', title: '当主の長女', breath: 'none', rank: '隠', haori: 'solid_white', color: '#ec4899' },
    { id: 'char_hinaki', name: '産屋敷ひなき', title: '当主の次女', breath: 'none', rank: '隠', haori: 'solid_white', color: '#f43f5e' },
    { id: 'char_tamayo', name: '珠世', title: '人を喰わぬ心優しき医者鬼', breath: 'blood', rank: '一般鬼', haori: 'plain', color: '#9333ea' },
    { id: 'char_yushiro', name: '愈史郎', title: '珠世に心酔する鬼の少年', breath: 'blood', rank: '一般鬼', haori: 'plain', color: '#22c55e' },
    { id: 'char_kanae', name: '胡蝶カナエ', title: '元花柱・しのぶの姉', breath: 'flower', rank: '柱', haori: 'butterfly_wing', color: '#d946ef' },
    { id: 'char_senjuro', name: '煉獄千寿郎', title: '炎柱の弟・誠実なる少年', breath: 'none', rank: '一般隊士', haori: 'solid_white', color: '#f59e0b' },
    { id: 'char_shinjuro', name: '煉獄槇寿郎', title: '元炎柱・剛毅の父', breath: 'flame', rank: '柱', haori: 'flame_edge', color: '#b91c1c' },
    { id: 'char_ruka', name: '煉獄瑠火', title: '強く優しき炎柱の母', breath: 'none', rank: '一般隊士', haori: 'solid_white', color: '#f97316' },
    { id: 'char_suma', name: '須磨（すま）', title: '音柱の妻・くのいち', breath: 'sound', rank: '一般隊士', haori: 'plain', color: '#ec4899' },
    { id: 'char_makio', name: 'まきを', title: '音柱の妻・くのいち', breath: 'sound', rank: '一般隊士', haori: 'plain', color: '#f97316' },
    { id: 'char_hinatsuru', name: '雛鶴（ひなつる）', title: '音柱の妻・くのいち', breath: 'sound', rank: '一般隊士', haori: 'plain', color: '#8b5cf6' },
    { id: 'char_jigoro', name: '桑島慈悟郎', title: '元鳴柱・善逸の師匠', breath: 'thunder', rank: '育手', haori: 'triangle_yellow', color: '#eab308' },
    { id: 'char_kaigaku_human', name: '獪岳（人間時）', title: '雷の呼吸の兄弟子', breath: 'thunder', rank: '丙', haori: 'plain', color: '#1e293b' },
    { id: 'char_tanjuro', name: '竈門炭十郎', title: '日の呼吸の継承父', breath: 'sun', rank: '育手', haori: 'checker_green', color: '#dc2626' },
    { id: 'char_kie', name: '竈門葵枝', title: '竈門家を支えし母', breath: 'none', rank: '隠', haori: 'plain', color: '#e2e8f0' },
    { id: 'char_takeo', name: '竈門竹雄', title: '炭治郎の長弟', breath: 'none', rank: '一般隊士', haori: 'plain', color: '#3b82f6' },
    { id: 'char_hanako', name: '竈門花子', title: '炭治郎の妹', breath: 'none', rank: '一般隊士', haori: 'plain', color: '#ec4899' },
    { id: 'char_shigeru', name: '竈門茂', title: '炭治郎の弟', breath: 'none', rank: '一般隊士', haori: 'plain', color: '#10b981' },
    { id: 'char_rokuta', name: '竈門六太', title: '竈門家の末っ子', breath: 'none', rank: '一般隊士', haori: 'plain', color: '#f59e0b' },
    { id: 'char_yoriichi', name: '継国縁壱', title: '始まりの呼吸の剣士・日神', breath: 'sun', rank: '柱', haori: 'solid_black', color: '#b91c1c' },
    { id: 'char_michikatsu', name: '継国巌勝（人間時）', title: '戦国時代の天才武士', breath: 'moon', rank: '柱', haori: 'solid_black', color: '#581c87' },
    { id: 'char_zero_type', name: '縁壱零式', title: '六本腕の戦闘用絡繰人形', breath: 'sun', rank: '刀鍛冶', haori: 'plain', color: '#7f1d1d' },
  ];

  for (const mem of SPECIAL_MEMBERS) {
    catalog.push({
      id: mem.id,
      catalogNo: currentNo++,
      name: mem.name,
      title: mem.title,
      role: mem.breath === 'blood' ? 'support' : 'slayer',
      rank: mem.rank as CorpsRank,
      breathStyle: mem.breath as BreathStyle,
      level: 5 + (currentNo % 10),
      exp: 0,
      nextExp: 50,
      stats: {
        maxHp: 70 + (currentNo % 30),
        hp: 70 + (currentNo % 30),
        maxBp: 30 + (currentNo % 20),
        bp: 30 + (currentNo % 20),
        attack: 28 + (currentNo % 15),
        defense: 20 + (currentNo % 10),
        speed: 18 + (currentNo % 15),
        luck: 20 + (currentNo % 15)
      },
      skills: [SKILLS.heal_herb, SKILLS.water_surface_slash],
      spriteConfig: {
        hairColor: '#1e293b',
        skinColor: '#fde68a',
        eyeColor: '#0f172a',
        haoriColor: mem.color,
        haoriPattern: mem.haori as any,
        hasSword: mem.rank !== '隠',
        accentColor: mem.color
      },
      lore: `鬼殺隊と関わりを深める重要人物。それぞれの想いを胸に鬼との戦いを支え抜く。`,
      isUnlocked: false
    });
  }

  // 4. Procedurally generate named Demon Slayer Corps members (ranks 甲 to 癸, 隠, 刀鍛冶)
  // precisely up to exactly 200 total characters. ZERO generic demons.
  const SURNAMES = [
    '佐々木', '佐藤', '鈴木', '高橋', '田中', '渡辺', '伊藤', '山本', '中村', '小林',
    '加藤', '吉田', '山田', '山口', '松本', '井上', '木村', '林', '斎藤', '清水',
    '山崎', '森', '池田', '橋本', '阿部', '石川', '山下', '中島', '石井', '小川',
    '前田', '岡田', '長谷川', '藤田', '後藤', '近藤', '村上', '遠藤', '青木', '坂本',
    '斉藤', '福田', '太田', '西村', '藤井', '金子', '三浦', '中野', '原田', '竹内'
  ];
  const GIVEN_NAMES = [
    '健一', '勇気', '大輔', '拓也', '翔太', '直樹', '亮平', '悠真', '蓮', '颯太',
    '大和', '陽向', '朝陽', '湊', '陸', '樹', '蒼', '陽翔', '結翔', '優真',
    '葵', '陽葵', '凛', '結菜', '芽依', '莉子', '咲良', '結月', '陽菜', '美咲',
    '美羽', '花', '紬', '結愛', '心春', '杏', '澪', '七海', '琴音', '千尋',
    '隼人', '一真', '京介', '宗佑', '武蔵', '小次郎', '玄十郎', '甚八', '伝蔵', '作之助'
  ];
  const RANKS: CorpsRank[] = ['甲', '乙', '丙', '丁', '戊', '己', '庚', '辛', '壬', '癸', '隠', '刀鍛冶'];
  const BREATH_STYLES: BreathStyle[] = ['water', 'flame', 'thunder', 'beast', 'flower', 'insect', 'mist', 'wind', 'stone', 'serpent'];

  while (currentNo <= 200) {
    const surname = SURNAMES[(currentNo * 7) % SURNAMES.length];
    const givenName = GIVEN_NAMES[(currentNo * 11) % GIVEN_NAMES.length];
    const rank = RANKS[currentNo % RANKS.length];
    const breath = rank === '隠' || rank === '刀鍛冶' ? 'none' : BREATH_STYLES[currentNo % BREATH_STYLES.length];
    const isSupport = rank === '隠' || rank === '刀鍛冶';

    const colors = ['#0284c7', '#dc2626', '#ca8a04', '#16a34a', '#9333ea', '#475569', '#0d9488', '#e11d48', '#2563eb'];
    const chosenColor = colors[currentNo % colors.length];

    catalog.push({
      id: `char_corps_${currentNo}`,
      catalogNo: currentNo,
      name: `${surname} ${givenName}`,
      title: `${rank}・${breath === 'none' ? (rank === '隠' ? '支援後方' : '鍛冶師') : breath + 'の呼吸手'}`,
      role: isSupport ? 'support' : 'slayer',
      rank: rank,
      breathStyle: breath,
      level: 1 + Math.floor(currentNo / 25),
      exp: 0,
      nextExp: 30 + currentNo,
      stats: {
        maxHp: 65 + (currentNo % 40),
        hp: 65 + (currentNo % 40),
        maxBp: 25 + (currentNo % 25),
        bp: 25 + (currentNo % 25),
        attack: 25 + Math.floor(currentNo / 10),
        defense: 18 + Math.floor(currentNo / 15),
        speed: 16 + (currentNo % 20),
        luck: 15 + (currentNo % 20)
      },
      skills: [
        SKILLS.heal_herb,
        breath === 'water' ? SKILLS.water_surface_slash :
        breath === 'thunder' ? SKILLS.thunder_clap :
        breath === 'flame' ? SKILLS.flame_tiger :
        SKILLS.beast_fangs
      ],
      spriteConfig: {
        hairColor: currentNo % 2 === 0 ? '#1e293b' : '#334155',
        skinColor: '#fed7aa',
        eyeColor: '#0f172a',
        haoriColor: chosenColor,
        haoriPattern: currentNo % 3 === 0 ? 'striped_purple' : 'plain',
        hasSword: !isSupport,
        accentColor: chosenColor
      },
      lore: `鬼殺隊に籍を置き、各々の呼吸と誇りをもって夜の闇に潜む鬼と戦い続ける選抜隊士。`,
      isUnlocked: false
    });
    currentNo++;
  }

  // 5. Add exactly 100 mob demons (雑魚鬼: Lv.1 - Lv.30, total 300 characters)
  // 手鬼に対抗した身体の一部鬼（足鬼・首鬼・耳鬼など）と、蜘蛛ではなくアリ・セミ・カブトなどの昆虫鬼！
  const MOB_DEMONS_DATA = [
    // Stage 1: 藤襲山・狭霧山・お堂・夜道 (Lv.1 - 3, Weak Stage for safe level training) - 25 demons
    // 身体の一部鬼 & 昆虫鬼
    { name: '足鬼（あしおに）', area: '藤襲山', lvl: 1, hp: 35, atk: 14, def: 8, spd: 16, horn: false, color: '#475569', feature: 'feet', lore: '手鬼に対抗し、無数の足を生やして高速疾走する藤襲山の雑魚鬼。' },
    { name: '首鬼（くびおに）', area: '藤襲山', lvl: 1, hp: 38, atk: 15, def: 7, spd: 12, horn: false, color: '#64748b', feature: 'neck', lore: '首が異常に長く伸びて暗闇から襲いかかる異形の雑魚鬼。' },
    { name: '地中アリ鬼（ちちゅうありおに）', area: '狭霧山', lvl: 1, hp: 40, atk: 16, def: 9, spd: 13, horn: true, color: '#334155', feature: 'ant', lore: 'アリのように地面に穴を掘り、隊士の足元から奇襲する昆虫鬼。' },
    { name: '幼虫セミ鬼（ようちゅうせみおに）', area: 'お堂', lvl: 1, hp: 42, atk: 15, def: 8, spd: 11, horn: false, color: '#52525b', feature: 'cicada', lore: 'セミの幼虫のように分厚い泥の殻を被った雑魚鬼。' },
    { name: '指鬼（ゆびおに）', area: '竹林', lvl: 1, hp: 44, atk: 17, def: 9, spd: 14, horn: false, color: '#3f3f46', feature: 'finger', lore: '両手足から巨大な10本の指が伸び、獲物を掴みかかる鬼。' },
    { name: '軍隊アリ鬼（ぐんたいありおに）', area: '古井戸', lvl: 2, hp: 46, atk: 17, def: 10, spd: 15, horn: true, color: '#1e293b', feature: 'ant', lore: '強い顎を持ち、獲物に噛みついて離さない凶暴なアリ鬼。' },
    { name: '鳴きセミ鬼（なきせみおに）', area: '荒野', lvl: 2, hp: 48, atk: 18, def: 10, spd: 13, horn: false, color: '#71717a', feature: 'cicada', lore: 'セミの怪音波を腹から放ち、耳を狂わせようとする昆虫鬼。' },
    { name: '耳鬼（みみおに）', area: '夜霧の森', lvl: 2, hp: 50, atk: 19, def: 11, spd: 15, horn: false, color: '#6b7280', feature: 'ear', lore: '巨大なコウモリのような耳で、隊士の呼吸音を遠くから察知する鬼。' },
    { name: '角カブト鬼（つのかぶとおに）', area: '廃屋', lvl: 2, hp: 52, atk: 19, def: 11, spd: 12, horn: true, color: '#4b5563', feature: 'beetle', lore: '頭に二股のカブトムシの角を生やし、猛烈な頭突きを仕掛ける鬼。' },
    { name: '大顎クワガタ鬼（おおあごくわがたおに）', area: '杉林', lvl: 2, hp: 53, atk: 20, def: 12, spd: 14, horn: true, color: '#374151', feature: 'stag', lore: 'クワガタの巨大なハサミで獲物を挟み潰す昆虫鬼。' },
    { name: '舌鬼（したおに）', area: '墓場', lvl: 2, hp: 55, atk: 20, def: 12, spd: 16, horn: false, color: '#1f2937', feature: 'tongue', lore: '2メートル以上伸びる長い毒舌を鞭のように振り回す雑魚鬼。' },
    { name: '腹鬼（はらおに）', area: '峠道', lvl: 2, hp: 56, atk: 21, def: 12, spd: 15, horn: false, color: '#525252', feature: 'belly', lore: '腹部に巨大な裂け目口を持ち、獲物を丸呑みにしようとする鬼。' },
    { name: '跳躍バッタ鬼（ちょうやくばったおに）', area: '雑木林', lvl: 3, hp: 58, atk: 22, def: 13, spd: 18, horn: false, color: '#404040', feature: 'grasshopper', lore: '長い後脚で木々を飛び跳ね、頭上から急降下キックを放つ昆虫鬼。' },
    { name: '眼鬼（めおに）', area: '渓谷', lvl: 3, hp: 60, atk: 22, def: 13, spd: 14, horn: false, color: '#78716c', feature: 'eye', lore: '顔や体に無数の赤い眼球が浮かび上がり、死角のない視野を持つ鬼。' },
    { name: '毒針ハチ鬼（どくばりはちおに）', area: '荒れ寺', lvl: 3, hp: 62, atk: 23, def: 14, spd: 17, horn: false, color: '#57534e', feature: 'wasp', lore: '蜂の毒針を尾に持ち、チクチクと急所を狙う昆虫鬼。' },
    { name: '歯鬼（はおに）', area: '山道', lvl: 3, hp: 64, atk: 24, def: 14, spd: 16, horn: true, color: '#44403c', feature: 'teeth', lore: '口いっぱいに三重の鋭い牙を生やし、骨まで噛み砕く鬼。' },
    { name: '羽アリ鬼（はねありおに）', area: '街道', lvl: 3, hp: 65, atk: 24, def: 14, spd: 17, horn: true, color: '#292524', feature: 'ant', lore: '黒い羽で低空を飛び回り、集団でまとわりつくアリ鬼。' },
    { name: '大鎌カマキリ鬼（おおがまかまきりおに）', area: '朽ち橋', lvl: 3, hp: 67, atk: 25, def: 15, spd: 16, horn: false, color: '#64748b', feature: 'mantis', lore: '両腕がノコギリ刃の巨大な鎌になっている凶暴なカマキリ鬼。' },
    { name: '腕鬼（うでおに）', area: '洞窟', lvl: 3, hp: 68, atk: 25, def: 15, spd: 15, horn: true, color: '#475569', feature: 'arm', lore: '背中から4本の剛腕を生やし、豪快な連続パンチを繰り出す鬼。' },
    { name: '油蝉鬼（あぶらぜみおに）', area: '廃村', lvl: 3, hp: 70, atk: 26, def: 16, spd: 15, horn: false, color: '#334155', feature: 'cicada', lore: 'ジリジリと灼熱の体液を滲ませ、激しい羽音で威嚇するセミ鬼。' },
    { name: '爪鬼（つめおに）', area: '藪の中', lvl: 3, hp: 70, atk: 26, def: 16, spd: 18, horn: false, color: '#1e293b', feature: 'claw', lore: '鋼鉄のように硬い10本の長い漆黒爪で木々ごと切り裂く鬼。' },
    { name: '怪光ホタル鬼（かいこうほたるおに）', area: '山林', lvl: 3, hp: 72, atk: 27, def: 16, spd: 16, horn: false, color: '#0f172a', feature: 'firefly', lore: '腹部が怪しく緑色に発光し、隊士の視界を眩惑する昆虫鬼。' },
    { name: '鼻鬼（はなおに）', area: '藤襲山', lvl: 3, hp: 74, atk: 27, def: 17, spd: 16, horn: true, color: '#581c87', feature: 'nose', lore: '異様に発達した嗅覚で、遠く離れた人間の血の匂いを正確に嗅ぎ分ける鬼。' },
    { name: '百足鬼（むかでおに）', area: '狭霧山', lvl: 3, hp: 75, atk: 28, def: 17, spd: 19, horn: true, color: '#4c1d95', feature: 'centipede', lore: '節くれ立った胴体と百本の足で木を登り、毒牙で噛みつくムカデ鬼。' },
    { name: '背鬼（せおに）', area: 'お堂', lvl: 3, hp: 76, atk: 28, def: 17, spd: 17, horn: false, color: '#3b0764', feature: 'back', lore: '背中に無数の骨の棘を生やし、背後からの攻撃を弾き返す鬼。' },

    // Stage 2: 浅草・市街地・川沿い (Lv.4 - 7) - 20 demons
    { name: '顎鬼（あごおに）', area: '浅草', lvl: 4, hp: 80, atk: 30, def: 18, spd: 18, horn: false, color: '#6b7280', feature: 'jaw', lore: '手鬼に対抗して強靭な顎を進化させ、地面ごと喰らいつく浅草の潜伏鬼。' },
    { name: 'スズメバチ鬼（すずめばちおに）', area: '浅草', lvl: 4, hp: 85, atk: 31, def: 19, spd: 22, horn: true, color: '#b91c1c', feature: 'wasp', lore: '猛烈なスピードで飛行し、致死性の毒針を突き刺す攻撃的な昆虫鬼。' },
    { name: '骨鬼（ほねおに）', area: '浅草', lvl: 4, hp: 88, atk: 32, def: 20, spd: 19, horn: true, color: '#991b1b', feature: 'bone', lore: '骨が皮膚を突き破って外骨格の鎧を形成した頑丈な鬼。' },
    { name: '赤トンボ鬼（あかとんぼおに）', area: '浅草', lvl: 4, hp: 90, atk: 33, def: 20, spd: 23, horn: false, color: '#7f1d1d', feature: 'dragonfly', lore: '4枚の細長い羽で急制動と急旋回を繰り返し、背後を取るトンボ鬼。' },
    { name: '膝鬼（ひざおに）', area: '浅草川辺', lvl: 5, hp: 95, atk: 34, def: 21, spd: 21, horn: false, color: '#0d9488', feature: 'knee', lore: '両膝から鋭利な角刃を生やし、跳び膝蹴りで襲いかかる異形鬼。' },
    { name: '重装カブト鬼（じゅうそうかぶとおに）', area: '倉庫街', lvl: 5, hp: 100, atk: 36, def: 24, spd: 17, horn: true, color: '#047857', feature: 'beetle', lore: '鋼鉄をも跳ね返す黒光りする甲殻を身にまとった怪力カブト鬼。' },
    { name: '拳鬼（こぶしおに）', area: '町外れ', lvl: 5, hp: 104, atk: 36, def: 22, spd: 20, horn: false, color: '#854d0e', feature: 'fist', lore: '岩石のような巨大な拳を振り回し、地響きを立てる異形鬼。' },
    { name: 'ダンゴムシ鬼（だんごむしおに）', area: '浅草裏通り', lvl: 5, hp: 108, atk: 37, def: 25, spd: 19, horn: false, color: '#a16207', feature: 'pillbug', lore: '丸まって硬い甲殻球体となり、転がり突進してくる昆虫鬼。' },
    { name: '肘鬼（ひじおに）', area: '市街地', lvl: 5, hp: 110, atk: 38, def: 24, spd: 22, horn: true, color: '#ca8a04', feature: 'elbow', lore: '両肘から骨の刃を突き出し、至近距離の肉弾戦で切り裂く鬼。' },
    { name: '鋸クワガタ鬼（のこぎりくわがたおに）', area: '大通り', lvl: 6, hp: 115, atk: 39, def: 25, spd: 24, horn: true, color: '#dc2626', feature: 'stag', lore: 'ギザギザの鋸刃のような大顎で刀をへし折ろうとするクワガタ鬼。' },
    { name: '踵鬼（かかとおに）', area: '馬車道', lvl: 6, hp: 118, atk: 40, def: 25, spd: 26, horn: false, color: '#ea580c', feature: 'heel', lore: '硬化させた踵で地面を砕き、強烈な斧のような踵落としを放つ鬼。' },
    { name: '水生タガメ鬼（すいせいたがめおに）', area: '堀端', lvl: 6, hp: 120, atk: 41, def: 26, spd: 23, horn: false, color: '#c2410c', feature: 'waterbug', lore: '強靭な前脚の鎌で獲物を水中に引きずり込もうとする昆虫鬼。' },
    { name: '毛鬼（けおに）', area: '地下暗渠', lvl: 6, hp: 122, atk: 41, def: 26, spd: 22, horn: false, color: '#431407', feature: 'hair', lore: '全身の剛毛を鉄針のように逆立て、全方位に針弾を飛ばす鬼。' },
    { name: '擬態カマキリ鬼（ぎたいかまきりおに）', area: '屋根の上', lvl: 6, hp: 125, atk: 42, def: 27, spd: 28, horn: false, color: '#312e81', feature: 'mantis', lore: '街並みと同化して気配を消し、一瞬で首を刈り取る暗殺カマキリ鬼。' },
    { name: '胸鬼（むねおに）', area: '大通り', lvl: 7, hp: 128, atk: 43, def: 28, spd: 25, horn: false, color: '#1e1b4b', feature: 'chest', lore: '胸部から無数の骨の肋骨檻を開閉させ、獲物を挟み捕らえる鬼。' },
    { name: 'コオロギ鬼（こおろぎおに）', area: '歓楽街', lvl: 7, hp: 130, atk: 44, def: 28, spd: 27, horn: true, color: '#701a75', feature: 'cricket', lore: '夜の闇で不気味な羽音を奏で、素早いステップで翻弄する昆虫鬼。' },
    { name: '喉鬼（のどおに）', area: '鉄橋下', lvl: 7, hp: 132, atk: 44, def: 29, spd: 24, horn: false, color: '#4a044e', feature: 'throat', lore: '喉が大きく膨らみ、衝撃波の咆哮を放って相手の体勢を崩す鬼。' },
    { name: 'イナゴ群れ鬼（いなごむれおに）', area: '電車道', lvl: 7, hp: 135, atk: 45, def: 29, spd: 28, horn: false, color: '#0f172a', feature: 'grasshopper', lore: '貪欲にすべてを喰らい尽くす、跳躍力と食欲に憑りつかれた昆虫鬼。' },
    { name: '掌鬼（てのひらおに）', area: '船着場', lvl: 7, hp: 138, atk: 46, def: 30, spd: 25, horn: false, color: '#0369a1', feature: 'palm', lore: '両掌に吸盤のような肉穴を持ち、触れた相手の生気を吸い取る鬼。' },
    { name: 'オニヤンマ鬼（おにやんまおに）', area: '郊外', lvl: 7, hp: 140, atk: 47, def: 31, spd: 29, horn: true, color: '#0284c7', feature: 'dragonfly', lore: '空中の覇者として急降下し、大顎で首元を狙う巨大トンボ鬼。' },

    // Stage 3: 南南東・鼓屋敷・山荘 (Lv.8 - 11) - 15 demons
    { name: '多足鬼（たそくおに）', area: '鼓屋敷', lvl: 8, hp: 145, atk: 48, def: 32, spd: 30, horn: false, color: '#78350f', feature: 'feet', lore: '手鬼に対抗して8本の足を自在に操り、壁や天井を疾走する異形鬼。' },
    { name: '毒針ケムシ鬼（どくばりけむしおに）', area: '鼓屋敷', lvl: 8, hp: 150, atk: 49, def: 33, spd: 27, horn: false, color: '#92400e', feature: 'caterpillar', lore: '触れるだけで激痛が走る毒毛を全身に蓄えた毛虫鬼。' },
    { name: '長首鬼（ながくびおに）', area: '鼓屋敷', lvl: 8, hp: 155, atk: 50, def: 34, spd: 28, horn: true, color: '#b45309', feature: 'neck', lore: '屋敷の障子を突き破り、自由自在に首をくねらせて噛みつく鬼。' },
    { name: '大百足鬼（おおむかでおに）', area: '鼓屋敷', lvl: 9, hp: 160, atk: 52, def: 35, spd: 32, horn: true, color: '#d97706', feature: 'centipede', lore: '巨躯を誇る百足の鬼。鋭い毒脚で廊下を這い回り獲物を締め上げる。' },
    { name: '多腕鬼（たわんおに）', area: '屋敷の土蔵', lvl: 9, hp: 165, atk: 53, def: 36, spd: 28, horn: true, color: '#65a30d', feature: 'arm', lore: '6本の筋骨隆々な腕で同時に殴りつける、手鬼の眷属に対抗する鬼。' },
    { name: '兵隊アリ鬼（へいたいありおに）', area: '天井裏', lvl: 9, hp: 170, atk: 54, def: 37, spd: 30, horn: true, color: '#4d7c0f', feature: 'ant', lore: '頑丈な頭部と大顎で屋敷の梁を噛み砕き、上から落下してくるアリ鬼。' },
    { name: '多眼鬼（たがんおに）', area: '屋敷の庭', lvl: 10, hp: 175, atk: 56, def: 38, spd: 27, horn: false, color: '#3f6212', feature: 'eye', lore: '360度すべての気配を捉える十数個の血走った目を持つ鬼。' },
    { name: '大甲虫カブト鬼（だいこうちゅうおに）', area: '奥の間', lvl: 10, hp: 180, atk: 57, def: 40, spd: 25, horn: true, color: '#15803d', feature: 'beetle', lore: '分厚い漆黒の甲殻で守られ、巨大な角で襖ごと突き破る鬼。' },
    { name: '長指鬼（ながゆびおに）', area: '鼓屋敷', lvl: 10, hp: 185, atk: 58, def: 39, spd: 29, horn: false, color: '#166534', feature: 'finger', lore: '触手のようにしなる長い指で隊士の手足を絡め取る異形鬼。' },
    { name: '女王バチ鬼（じょおうばちおに）', area: '鼓屋敷', lvl: 10, hp: 190, atk: 60, def: 41, spd: 31, horn: true, color: '#14532d', feature: 'wasp', lore: '鋭い毒針を連続で撃ち出し、隊士の自由を奪う高慢な蜂鬼。' },
    { name: '長舌鬼（ながしたおに）', area: '茶室', lvl: 11, hp: 195, atk: 61, def: 42, spd: 30, horn: false, color: '#047857', feature: 'tongue', lore: '茶室の隅から天井を伝って舌を伸ばし、日輪刀を絡め取ろうとする鬼。' },
    { name: '大鋏クワガタ鬼（おおはさみおに）', area: '回廊', lvl: 11, hp: 200, atk: 62, def: 44, spd: 28, horn: true, color: '#065f46', feature: 'stag', lore: '鉄の柱をも両断する鋼の大ハサミを持つ、回廊の守護昆虫鬼。' },
    { name: '剛脚鬼（ごうきゃくおに）', area: '裏山', lvl: 11, hp: 205, atk: 63, def: 43, spd: 33, horn: false, color: '#064e3b', feature: 'feet', lore: '丸太のように太い脚から放たれる回し蹴りで大木を薙ぎ倒す鬼。' },
    { name: 'カメムシ鬼（かめむしおに）', area: '床下', lvl: 11, hp: 210, atk: 64, def: 45, spd: 26, horn: false, color: '#0f766e', feature: 'stinkbug', lore: '激しい刺激臭の毒ガスを噴射して隊士の呼吸を妨害する昆虫鬼。' },
    { name: '狂乱セミ鬼（きょうらんせみおに）', area: '鼓屋敷中心', lvl: 11, hp: 215, atk: 65, def: 46, spd: 32, horn: false, color: '#115e59', feature: 'cicada', lore: '鼓の音に合わせて激しく鳴き叫び、屋敷中に超音波を反響させる鬼。' },

    // Stage 4: 森林・山林 (蜘蛛ではなく昆虫と身体部位！ Lv.12 - 16) - 15 demons
    { name: '百足足鬼（むかでそくおに）', area: '深山', lvl: 12, hp: 220, atk: 66, def: 45, spd: 34, horn: false, color: '#6d28d9', feature: 'feet', lore: '手鬼への対抗心から全身に無数の足を生やした山林の異形鬼。' },
    { name: '巨角カブト鬼（きょかくかぶとおに）', area: '老木林', lvl: 12, hp: 225, atk: 67, def: 46, spd: 30, horn: true, color: '#5b21b6', feature: 'beetle', lore: '巨木をもへし折る一本角を誇る、森の重量級昆虫鬼。' },
    { name: '双首鬼（そうしゅおに）', area: '霧の谷', lvl: 13, hp: 230, atk: 68, def: 47, spd: 33, horn: false, color: '#4c1d95', feature: 'neck', lore: '左右に二つの首を持ち、同時に異なる方向へ噛みついてくる鬼。' },
    { name: '大顎軍隊アリ鬼（おおあごありおに）', area: '腐葉土', lvl: 13, hp: 235, atk: 70, def: 48, spd: 35, horn: true, color: '#7e22ce', feature: 'ant', lore: '地面から群れを成して湧き出し、骨まで喰らい尽くす黒アリ鬼。' },
    { name: '大飛蝗バッタ鬼（だいひこうばったおに）', area: '樹林', lvl: 13, hp: 240, atk: 71, def: 49, spd: 37, horn: false, color: '#6b21a8', feature: 'grasshopper', lore: '森の上空高く跳び上がり、閃光のような蹴りを見舞うバッタ鬼。' },
    { name: '八腕鬼（はちわんおに）', area: '岩場', lvl: 14, hp: 245, atk: 72, def: 50, spd: 32, horn: true, color: '#581c87', feature: 'arm', lore: '8本の腕を風車のように回転させて攻撃を弾き返す異形鬼。' },
    { name: '凶毒スズメバチ鬼（きょうどくはちおに）', area: '樹幹', lvl: 14, hp: 250, atk: 74, def: 52, spd: 38, horn: true, color: '#3b0764', feature: 'wasp', lore: '激痛と麻痺を引き起こす黒紫の毒針を尾から乱射する蜂鬼。' },
    { name: '大耳鬼（おおみみおに）', area: '登山道', lvl: 14, hp: 255, atk: 75, def: 51, spd: 34, horn: false, color: '#831843', feature: 'ear', lore: '木々のざわめきの中から隊士の心音を聞き分け、先回りする鬼。' },
    { name: '双鎌カマキリ鬼（そうれんかまきりおに）', area: '竹林深部', lvl: 15, hp: 260, atk: 76, def: 53, spd: 39, horn: false, color: '#9d174d', feature: 'mantis', lore: '両手の鎌で二連斬撃を繰り出し、竹林を一瞬で両断する鬼。' },
    { name: '百目鬼（ひゃくめおに）', area: '胞子の谷', lvl: 15, hp: 265, atk: 77, def: 54, spd: 35, horn: false, color: '#be185d', feature: 'eye', lore: '全身を覆う無数の目が一斉に光り、隙の糸を見えにくくする異形鬼。' },
    { name: '深山クワガタ鬼（みやまくわがたおに）', area: '老木群', lvl: 15, hp: 270, atk: 78, def: 55, spd: 36, horn: true, color: '#db2777', feature: 'stag', lore: '黄金の微毛に覆われた頭部突起と湾曲した鋭いハサミを持つクワガタ鬼。' },
    { name: '百足大爪鬼（むかでつめおに）', area: '巨岩地帯', lvl: 15, hp: 275, atk: 79, def: 56, spd: 37, horn: true, color: '#475569', feature: 'claw', lore: '無数の足の先がすべて鋭利な鉤爪になっている山林の恐るべき鬼。' },
    { name: '怪音セミ鬼（かいおんせみおに）', area: '樹林山頂', lvl: 16, hp: 280, atk: 80, def: 57, spd: 38, horn: false, color: '#334155', feature: 'cicada', lore: '木霊する大音量の鳴き声で相手の平衡感覚を狂わせるセミ鬼。' },
    { name: '外骨格甲虫鬼（こうちゅうおに）', area: '山頂岩峰', lvl: 16, hp: 290, atk: 82, def: 58, spd: 35, horn: true, color: '#1e293b', feature: 'beetle', lore: '全身を厚さ数寸の黒い昆虫甲殻で覆い、日輪刀の刃を弾こうとする鬼。' },
    { name: '十指縛り鬼（じっししばりおに）', area: '山頂奥', lvl: 16, hp: 300, atk: 84, def: 60, spd: 39, horn: true, color: '#0f172a', feature: 'finger', lore: '手鬼を超える長さの十本指を自在に伸ばし獲物を捕獲する異形鬼。' },

    // Stage 5: 無限列車・線路 (Lv.17 - 20) - 10 demons
    { name: '鉄輪足鬼（てつりんあしおに）', area: '無限列車', lvl: 17, hp: 310, atk: 85, def: 60, spd: 42, horn: false, color: '#1e1b4b', feature: 'feet', lore: '列車の車輪と融合した頑強な足を回転させて疾走する鬼。' },
    { name: '煤煙セミ鬼（ばいえんせみおに）', area: '機関車', lvl: 17, hp: 320, atk: 86, def: 62, spd: 38, horn: false, color: '#18181b', feature: 'cicada', lore: '機関車の煙突から黒煙を吸い、煤の混じった怪音波を吐き出すセミ鬼。' },
    { name: '鉄甲カブト鬼（てっこうかぶとおに）', area: '炭水車', lvl: 18, hp: 335, atk: 88, def: 64, spd: 39, horn: true, color: '#27272a', feature: 'beetle', lore: '石炭のように黒く硬い角で客車の壁を突き破るカブト鬼。' },
    { name: '線路アリ鬼（せんろありおに）', area: '床下車輪', lvl: 18, hp: 350, atk: 90, def: 65, spd: 43, horn: true, color: '#3f3f46', feature: 'ant', lore: '線路のレールにしがみつき、車輪の下から大顎で足を狙うアリ鬼。' },
    { name: '肉塊首鬼（にくかいしゅおに）', area: '車両連結部', lvl: 18, hp: 365, atk: 91, def: 66, spd: 37, horn: true, color: '#52525b', feature: 'neck', lore: '連結部に巻き付くように伸びた何重もの首で乗客を狙う異形鬼。' },
    { name: '強風トンボ鬼（きょうふうとんぼおに）', area: '客車屋根', lvl: 19, hp: 380, atk: 93, def: 68, spd: 46, horn: false, color: '#71717a', feature: 'dragonfly', lore: '疾走する列車の屋根の上で、強風に逆らって飛行するトンボ鬼。' },
    { name: '夢幻ホタル鬼（むげんほたるおに）', area: '客席', lvl: 19, hp: 390, atk: 94, def: 69, spd: 44, horn: false, color: '#0284c7', feature: 'firefly', lore: '客席を漂う青白い光で乗客を心地よい眠りへと誘うホタル鬼。' },
    { name: '剛腕拳鬼（ごうわんけんおに）', area: '線路沿い', lvl: 20, hp: 400, atk: 96, def: 70, spd: 41, horn: true, color: '#0369a1', feature: 'fist', lore: '巨大な鉄塊のような拳で線路の枕木を叩き割りながら追走する鬼。' },
    { name: '大鋏鋸鬼（おおはさみのこおに）', area: '煙突付近', lvl: 20, hp: 410, atk: 97, def: 71, spd: 45, horn: true, color: '#075985', feature: 'stag', lore: '煙突の鉄板をも断ち切る鋭利な鋸刃の大顎を持つクワガタ鬼。' },
    { name: '触手長指鬼（しょくしゅながゆびおに）', area: '客車内壁', lvl: 20, hp: 420, atk: 98, def: 72, spd: 47, horn: true, color: '#0c4a6e', feature: 'finger', lore: '列車内壁と同化し、無数の指先から肉の触手を伸ばす異形鬼。' },

    // Stage 6: 吉原遊郭・花街 (Lv.21 - 24) - 8 demons
    { name: '紅艶舌鬼（こうえんぜつおに）', area: '吉原遊郭', lvl: 21, hp: 440, atk: 100, def: 74, spd: 46, horn: false, color: '#831843', feature: 'tongue', lore: '紅を引いた唇から艶やかな長舌を伸ばして獲物を絡め取る花街の鬼。' },
    { name: '大門カマキリ鬼（おおもんかまきりおに）', area: '吉原大門', lvl: 21, hp: 455, atk: 102, def: 75, spd: 48, horn: false, color: '#9d174d', feature: 'mantis', lore: '大門の影に潜み、華麗な二刀流の鎌で侵入者を迎え撃つカマキリ鬼。' },
    { name: '幻惑夜光ホタル鬼（げんわくほたるおに）', area: '見世棚', lvl: 22, hp: 470, atk: 104, def: 76, spd: 48, horn: false, color: '#be185d', feature: 'firefly', lore: '吉原の灯篭に紛れて妖艶な光を放ち、幻術で惑わすホタル鬼。' },
    { name: '帯刃首鬼（おびばしゅおに）', area: '妓楼屋根裏', lvl: 22, hp: 485, atk: 106, def: 78, spd: 50, horn: false, color: '#db2777', feature: 'neck', lore: '首が帯のように薄く長く伸び、刃物のようにしなって切り裂く鬼。' },
    { name: '水路タガメ鬼（すいろたがめおに）', area: 'お歯黒どぶ', lvl: 23, hp: 500, atk: 108, def: 79, spd: 49, horn: true, color: '#0f766e', feature: 'waterbug', lore: 'どぶ川の泥底に潜み、怪力の前脚で獲物を引きずり込むタガメ鬼。' },
    { name: '怪力剛腕鬼（かいりきごうわんおに）', area: '裏長屋', lvl: 23, hp: 515, atk: 110, def: 81, spd: 47, horn: true, color: '#115e59', feature: 'arm', lore: '四本の腕で長屋の壁を破壊しながら突進してくる重量級異形鬼。' },
    { name: '紅楼鋭爪鬼（こうろうえいそうおに）', area: '紅楼', lvl: 24, hp: 530, atk: 112, def: 82, spd: 52, horn: false, color: '#9f1239', feature: 'claw', lore: '漆塗りのように赤い十本の爪で、風を切り裂きながら襲いかかる鬼。' },
    { name: '猛毒スズメバチ女王鬼（じょおうばちおに）', area: '仲ノ町通り', lvl: 24, hp: 545, atk: 114, def: 84, spd: 53, horn: true, color: '#881337', feature: 'wasp', lore: '夜桜の舞う仲ノ町通りに君臨し、猛毒の針弾を乱射する凶悪な蜂鬼。' },

    // Stage 7 & 8: 刀鍛冶の里 & 無限城 (Lv.25 - 30) - 7 demons
    { name: '甲殻重装カブト鬼（じゅうそうかぶとおに）', area: '刀鍛冶の里', lvl: 25, hp: 560, atk: 116, def: 85, spd: 53, horn: true, color: '#0284c7', feature: 'beetle', lore: '鍛冶場の熱にも耐える漆黒のダイヤモンド甲殻を持つ巨角カブト鬼。' },
    { name: '大鋏金剛クワガタ鬼（こんごうくわがたおに）', area: '鍛冶場', lvl: 26, hp: 580, atk: 118, def: 86, spd: 54, horn: true, color: '#0369a1', feature: 'stag', lore: '鍛造された名刀さえも噛み砕く、金剛石のように硬いハサミの昆虫鬼。' },
    { name: '鉱山剛足鬼（こうざんごうそくおに）', area: '里の鉱山', lvl: 26, hp: 600, atk: 120, def: 88, spd: 55, horn: true, color: '#b45309', feature: 'feet', lore: '鉱石の混ざった岩石の足で地面を踏み砕き、地響きを起こす異形鬼。' },
    { name: '無限城百足鬼（むげんじょうむかでおに）', area: '無限城', lvl: 27, hp: 625, atk: 122, def: 90, spd: 56, horn: true, color: '#18181b', feature: 'centipede', lore: '無限城の反転する回廊を縦横無尽に這い回る、百本の足を持つ凶悪鬼。' },
    { name: '反転複眼鬼（はんてんふくがんおに）', area: '無限城回廊', lvl: 28, hp: 650, atk: 125, def: 92, spd: 57, horn: true, color: '#27272a', feature: 'eye', lore: '次元の歪む無限城の空間をすべて見通す無数の血眼を持つ異形鬼。' },
    { name: '天翔オニヤンマ鬼（てんしょうおにやんまおに）', area: '反転の間', lvl: 29, hp: 680, atk: 128, def: 94, spd: 60, horn: false, color: '#3f3f46', feature: 'dragonfly', lore: '重力の狂った無限城の空間を自在に飛行し、急降下強襲を仕掛ける鬼。' },
    { name: '無惨直属・多肢手足鬼（たしたいしゅそくおに）', area: '無限城深奥', lvl: 30, hp: 710, atk: 130, def: 96, spd: 62, horn: true, color: '#7f1d1d', feature: 'arm_feet', lore: '手鬼の無数の手と、足鬼の無数の足を併せ持つ無惨の細胞異形。' },
  ];

  for (const mob of MOB_DEMONS_DATA) {
    if (currentNo > 300) break;
    const mobIndex = currentNo - 200;
    catalog.push({
      id: `demon_mob_${mobIndex}`,
      catalogNo: currentNo,
      name: mob.name,
      title: `${mob.area}の野良鬼 (Lv.${mob.lvl})`,
      role: 'demon',
      rank: mob.lvl <= 4 ? '一般鬼' : '異形鬼',
      breathStyle: 'blood',
      level: mob.lvl,
      exp: 0,
      nextExp: 0,
      stats: {
        maxHp: mob.hp,
        hp: mob.hp,
        maxBp: 20 + mob.lvl * 2,
        bp: 20 + mob.lvl * 2,
        attack: mob.atk,
        defense: mob.def,
        speed: mob.spd,
        luck: 10 + (mob.lvl % 10)
      },
      skills: mob.lvl >= 8
        ? [SKILLS.mob_scratch, SKILLS.mob_bite, SKILLS.mob_dark_roar]
        : mob.lvl >= 4
        ? [SKILLS.mob_scratch, SKILLS.mob_bite]
        : [SKILLS.mob_scratch],
      spriteConfig: {
        hairColor: currentNo % 2 === 0 ? '#1e293b' : '#3f3f46',
        skinColor: currentNo % 3 === 0 ? '#94a3b8' : currentNo % 3 === 1 ? '#cbd5e1' : '#64748b',
        eyeColor: mob.lvl >= 10 ? '#dc2626' : '#ef4444',
        haoriColor: mob.color,
        haoriPattern: mob.lvl >= 8 ? 'demon_mark' : 'spotted',
        hasHorn: mob.horn,
        accentColor: mob.color
      },
      lore: mob.lore || `${mob.area}周辺を徘徊し、人を喰らう下級の野良鬼。修業やレベル上げに適している。日輪刀で頸を断つことで消滅する。`,
      isUnlocked: false
    });
    currentNo++;
  }

  return catalog;
}
